name: Assign weekly updates reminder

on:
  issues:
    types: [opened, edited]

jobs:
  add-bug-to-project:
    runs-on: ubuntu-latest
    steps:
    - name: Add weekly updates issue project
      uses: actions/add-to-project@main
      with:
        project-url: https://github.com/users/NicolasOmar/projects/3
        github-token: ${{ secrets.ADD_TO_REACTIVE_BULMA_PROJECT }}
        labeled: dependencies, enhancement
        label-operator: AND