name: Release version

on:
  push:
    branches: ["main"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: 1/4 | Checkout repo
      uses: actions/checkout@v5
    - name: 2/4 | Setup Node environment
      uses: actions/setup-node@v5
      with:
        node-version: latest
    - name: 3/4 | Install dependencies
      run: npm ci
    - name: 4/4 | Run Semantic Release script
      run: npm run semantic-release
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
